language: node_js
node_js:
   - "7"
install: npm install
script: node build/script.build.js "mat"
deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   on:
      branch: master
   local_dir: dist
   target_branch: gh-pages
